version: '3'
services:

  # app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   depends_on:
  #     - postgres

   postgres:
        image: 'postgres:14.2'
        ports:
          - "5432:5432"
        restart: always
        deploy:
          mode: replicated
          replicas: 1
        environment:
          POSTGRES_USER: vijay
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: users
        volumes:
            - ./db/postgres/:/var/lib/postgresql